# Generated by Django 4.1.2 on 2022-11-01 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StaffModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('empId', models.CharField(max_length=250)),
                ('empDepartment', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254)),
                ('profile', models.ImageField(null=True, upload_to='images/')),
                ('date_of_birth', models.CharField(max_length=250)),
                ('password', models.CharField(max_length=250)),
                ('official_email', models.EmailField(max_length=254, null=True)),
                ('state', models.CharField(max_length=250)),
                ('country', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=250)),
                ('pin', models.CharField(max_length=250)),
                ('join_date', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'staff_details',
            },
        ),
    ]
