# Generated by Django 4.1.2 on 2022-11-01 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffmodel',
            name='email',
        ),
        migrations.AddField(
            model_name='staffmodel',
            name='to',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
