# Generated by Django 4.1.2 on 2022-11-02 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_remove_staffmodel_email_staffmodel_to'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staffmodel',
            old_name='id',
            new_name='staff_id',
        ),
    ]
