# Generated by Django 4.1.1 on 2022-11-12 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_rename_id_staffmodel_staff_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffmodel',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='staffmodel',
            name='password',
        ),
    ]
