# Generated by Django 4.1.1 on 2022-11-12 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_remove_staffmodel_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffmodel',
            name='password',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
