# Generated by Django 4.1.2 on 2022-11-02 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminapp', '0003_rename_id_staffmodel_staff_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfidentialDataModel',
            fields=[
                ('data_id', models.AutoField(primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=250)),
                ('data_file', models.FileField(null=True, upload_to='confidential_files/')),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.staffmodel')),
            ],
            options={
                'db_table': 'private_data',
            },
        ),
    ]
