# Generated by Django 4.1.2 on 2022-11-03 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_rename_id_staffmodel_staff_id'),
        ('userapp', '0002_confidentialdatamodel_published_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request_recordModel',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('request_title', models.CharField(max_length=250)),
                ('request_file', models.CharField(max_length=250)),
                ('department', models.CharField(max_length=250)),
                ('request_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='pending', max_length=250)),
                ('receiver_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='adminapp.staffmodel')),
                ('sender_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='adminapp.staffmodel')),
            ],
            options={
                'db_table': 'request_data',
            },
        ),
    ]
