# Generated by Django 4.1.2 on 2022-11-04 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0004_request_recordmodel_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request_recordmodel',
            name='status',
            field=models.CharField(default='sent', max_length=250),
        ),
    ]
