# Generated by Django 4.1.2 on 2022-11-04 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_rename_id_staffmodel_staff_id'),
        ('userapp', '0005_alter_request_recordmodel_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Send_request_files',
            fields=[
                ('send_file_id', models.AutoField(primary_key=True, serialize=False)),
                ('name_of_the_file', models.CharField(max_length=250)),
                ('file', models.FileField(null=True, upload_to='from_receiver/')),
                ('description', models.CharField(max_length=250)),
                ('receiver_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver1', to='adminapp.staffmodel')),
                ('sender_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender1', to='adminapp.staffmodel')),
            ],
            options={
                'db_table': 'files_from_request_receiver',
            },
        ),
    ]
