# Generated by Django 4.1.2 on 2022-11-04 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0006_send_request_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='send_request_files',
            name='status',
            field=models.CharField(default='sent', max_length=250),
        ),
    ]
