# Generated by Django 4.1.2 on 2022-11-04 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_rename_id_staffmodel_staff_id'),
        ('userapp', '0007_send_request_files_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='send_request_files',
            name='sender_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.staffmodel'),
        ),
    ]
