# Generated by Django 4.1.2 on 2022-11-04 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0008_alter_send_request_files_sender_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='send_request_files',
            name='receiver_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver1', to='userapp.request_recordmodel'),
        ),
        migrations.AlterField(
            model_name='send_request_files',
            name='sender_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.request_recordmodel'),
        ),
    ]
