# Generated by Django 4.1.2 on 2022-11-05 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0009_alter_send_request_files_receiver_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='send_request_files',
            old_name='receiver_id',
            new_name='receiver_id1',
        ),
        migrations.RenameField(
            model_name='send_request_files',
            old_name='sender_id',
            new_name='sender_id1',
        ),
    ]
