# Generated by Django 4.1.2 on 2022-11-05 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_rename_id_staffmodel_staff_id'),
        ('userapp', '0011_remove_send_request_files_receiver_id1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='send_request_files',
            name='receiver_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receiver_id', to='adminapp.staffmodel'),
        ),
        migrations.AddField(
            model_name='send_request_files',
            name='sender_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender_id', to='adminapp.staffmodel'),
        ),
    ]
