# Generated by Django 4.1.2 on 2022-11-10 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0015_request_recordmodel_qr_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request_recordmodel',
            name='request_file',
        ),
    ]
